import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/style/globals.css";
import Menu from "@/component/Menu"
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { NextIntlClientProvider, hasLocale } from "next-intl";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
type Props = {
  params: { locale: string | Promise<{ locale: string }> }
};

export async function generateMetadata({ params }: Props): Promise<Metadata>{
  //  const { locale } = await params;
  const awaitedParams = await params;
  const { locale } = awaitedParams;
   return{
      openGraph:{
        locale:`${locale}`,
      },
   }
}


export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{locale:string}>
}>) {
  const {locale} = await params;
  if(!hasLocale(routing.locales, locale)){
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider>
          <Menu/>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
